export const dataProducts = [
  {
    "id": 1,
    "name": "Mouse",
    "img": "profile.jpg",
    "stars": 3.5,
    "stock": 10,
    "price": 19,
    "id_unico": "A1B2C3D4E5",
    "descrip": "Un ratón ergonómico y preciso para facilitar la navegación y el trabajo en la computadora.",
    "date": "2024-04-01",
    "category": "comida"
  },
  {
    "id": 2,
    "name": "Reglas",
    "img": "profile.jpg",
    "stars": 3.5,
    "stock": 30,
    "price": 14,
    "id_unico": "F6G7H8I9J0",
    "descrip": "Conjunto de reglas de diferentes longitudes, ideales para trazar líneas y mediciones precisas en proyectos escolares o de oficina.",
    "date": "2024-03-15",
    "category": "bebidas"
  },
  {
    "id": 3,
    "name": "Libreta",
    "img": "profile.jpg",
    "stars": 1.0,
    "stock": 50,
    "price": 12,
    "id_unico": "K1L2M3N4O5",
    "descrip": "Una libreta con tapa dura perfecta para tomar notas, hacer bocetos o escribir pensamientos.",
    "date": "2024-02-28",
    "category": "dulceria"
  },
  {
    "id": 4,
    "name": "Bolígrafo",
    "img": "profile.jpg",
    "stars": 2.0,
    "stock": 100,
    "price": 16,
    "id_unico": "P6Q7R8S9T0",
    "descrip": "Un bolígrafo de tinta suave y duradera, ideal para escribir de forma cómoda y sin esfuerzo.",
    "date": "2024-03-10",
    "category": "dulceria"
  },
  {
    "id": 5,
    "name": "Lápiz",
    "img": "profile.jpg",
    "stars": 3.5,
    "stock": 87,
    "price": 9,
    "id_unico": "U1V2W3X4Y5",
    "descrip": "Un lápiz de grafito resistente y de alta calidad, perfecto para dibujar, tomar notas o hacer esbozos.",
    "date": "2024-01-20",
    "category": "postres"
  },
  {
    "id": 6,
    "name": "Papel",
    "img": "profile.jpg",
    "stars": 3.0,
    "stock": 19,
    "price": 17,
    "id_unico": "Z6A7B8C9D0",
    "descrip": "Un paquete de papel de alta blancura y suavidad, ideal para imprimir documentos, notas o dibujos.",
    "date": "2024-03-05",
    "category": "postres"
  },
  {
    "id": 7,
    "name": "Cinta Adhesiva",
    "img": "profile.jpg",
    "stars": 3.5,
    "stock": 70,
    "price": 13,
    "id_unico": "E1F2G3H4I5",
    "descrip": "Una cinta adhesiva transparente y resistente, perfecta para envolver regalos, sellar sobres o reparaciones rápidas.",
    "date": "2024-02-10",
    "category": "bebidas"
  },
  {
    "id": 8,
    "name": "Cuaderno",
    "img": "profile.jpg",
    "stars": 5.0,
    "stock": 80,
    "price": 15,
    "id_unico": "J6K7L8M9N0",
    "descrip": "Un cuaderno de tapa dura y papel de calidad, ideal para tomar apuntes en clase, hacer listas o llevar un diario.",
    "date": "2024-03-20",
    "category": "dulceria"
  },
  {
    "id": 9,
    "name": "Calculadora",
    "img": "profile.jpg",
    "stars": 4.0,
    "stock": 50,
    "price": 29,
    "id_unico": "O1P2Q3R4S5",
    "descrip": "Una calculadora con funciones básicas y avanzadas, perfecta para cálculos matemáticos en la escuela, el trabajo o en casa.",
    "date": "2024-02-15",
    "category": "comida"
  },
  {
    "id": 10,
    "name": "Tijeras",
    "img": "profile.jpg",
    "stars": 3.5,
    "stock": 30,
    "price": 11,
    "id_unico": "T6U7V8W9X0",
    "descrip": "Un par de tijeras de acero inoxidable con hojas afiladas y mango ergonómico, ideales para cortar papel, tela o manualidades.",
    "date": "2024-01-25",
    "category": "postres"
  },
  {
    "id": 11,
    "name": "Grapadora",
    "img": "profile.jpg",
    "stars": 4.0,
    "stock": 25,
    "price": 8,
    "id_unico": "A1B2C3D4E6",
    "descrip": "Una grapadora compacta y resistente, ideal para organizar documentos o trabajos escolares.",
    "date": "2024-03-12",
    "category": "bebidas"
  },
  {
    "id": 12,
    "name": "Pegamento",
    "img": "profile.jpg",
    "stars": 3.0,
    "stock": 40,
    "price": 5,
    "id_unico": "F6G7H8I9J1",
    "descrip": "Un pegamento de secado rápido y resistente, perfecto para manualidades, reparaciones rápidas o proyectos escolares.",
    "date": "2024-02-18",
    "category": "bebidas"
  },
  {
    "id": 13,
    "name": "Calculadora Científica",
    "img": "profile.jpg",
    "stars": 4.5,
    "stock": 15,
    "price": 24,
    "id_unico": "K1L2M3N4O6",
    "descrip": "Una calculadora científica con funciones avanzadas, ideal para estudiantes de matemáticas, física o ingeniería.",
    "date": "2024-03-08",
    "category": "comida"
  },
  {
    "id": 14,
    "name": "Marcadores de Colores",
    "img": "profile.jpg",
    "stars": 4.0,
    "stock": 50,
    "price": 7,
    "id_unico": "P6Q7R8S9T1",
    "descrip": "Un conjunto de marcadores de colores vibrantes, perfectos para resaltar textos o hacer diagramas en papel.",
    "date": "2024-02-22",
    "category": "dulceria"
  },
  {
    "id": 15,
    "name": "Borrador",
    "img": "profile.jpg",
    "stars": 3.0,
    "stock": 60,
    "price": 3,
    "id_unico": "U1V2W3X4Y6",
    "descrip": "Un borrador suave y eficaz, ideal para corregir errores en lápiz o tinta sobre papel.",
    "date": "2024-01-30",
    "category": "dulceria"
  },
  {
    "id": 16,
    "name": "Destornillador",
    "img": "profile.jpg",
    "stars": 4.5,
    "stock": 20,
    "price": 10,
    "id_unico": "Z6A7B8C9D1",
    "descrip": "Un destornillador multifuncional con cabezales intercambiables, ideal para reparaciones en el hogar o el trabajo.",
    "date": "2024-03-25",
    "category": "postres"
  },
  {
    "id": 17,
    "name": "Papel de Notas",
    "img": "profile.jpg",
    "stars": 3.5,
    "stock": 100,
    "price": 6,
    "id_unico": "E1F2G3H4I6",
    "descrip": "Un bloc de papel de notas adhesivas, perfecto para tomar apuntes rápidos o dejar mensajes.",
    "date": "2024-02-05",
    "category": "dulceria"
  },
  {
    "id": 18,
    "name": "Carpeta de Archivos",
    "img": "profile.jpg",
    "stars": 4.0,
    "stock": 35,
    "price": 12,
    "id_unico": "J6K7L8M9N1",
    "descrip": "Una carpeta de archivos resistente y organizada, perfecta para almacenar documentos importantes.",
    "date": "2024-03-18",
    "category": "bebidas"
  },
  {
    "id": 19,
    "name": "Pila AA",
    "img": "profile.jpg",
    "stars": 4.0,
    "stock": 50,
    "price": 4,
    "id_unico": "O1P2Q3R4S6",
    "descrip": "Una pila AA de larga duración, ideal para dispositivos electrónicos como controles remotos o juguetes.",
    "date": "2024-01-10",
    "category": "comida"
  },
  {
    "id": 20,
    "name": "Rotuladores Permanentes",
    "img": "profile.jpg",
    "stars": 3.5,
    "stock": 25,
    "price": 8,
    "id_unico": "T6U7V8W9X1",
    "descrip": "Un conjunto de rotuladores permanentes de punta fina, ideales para escribir en superficies como plástico, metal o vidrio.",
    "date": "2024-02-02",
    "category": "accesorios"
  }
];


export const users = [
  {
    id: 1,
    img: 'jorge.png',
    state: 'online',
    name: 'jorge',
    order: 'ORD12382',
    div: 'DACYTI',
    edi: 'Edicio H'
  },
  {
    id: 2,
    img: 'jacquelina.png',
    state: 'offline',
    name: 'jacquelina',
    order: 'ORD12345',
    div: 'DAIA',
    edi: 'Edicio A'
  },
  {
    id: 3,
    img: 'loya.png',
    state: 'offline',
    name: 'loya',
    order: 'ORD12398',
    div: 'DACB',
    edi: 'Edicio X'
  },
]